from model import *
"""
pretty good values
H = 0.2
LAMBDA = 0.05 
WEIGHTS = [1.0008, 1]
"""

NUM_AGENTS = 5
INITIAL_VARIANT_OCCURENCE = 0.75
H = 0.2
LAMBDA = 0.03
WEIGHTS = [1.0006, 1]
NUM_SIMULATIONS = 2
NUM_CHILD_PER_ADULT = 3
USE_GEN_REPLACE = True 
THRESHHOLD = 0.99
THREE_GEN_EXACT = True

setup_model(NUM_AGENTS, INITIAL_VARIANT_OCCURENCE, H, LAMBDA, WEIGHTS, NUM_SIMULATIONS, USE_GEN_REPLACE, NUM_CHILD_PER_ADULT, THRESHHOLD, THREE_GEN_EXACT)