from model import *

NUM_AGENTS = 100
INITIAL_VARIANT_OCCURENCE = 0.75
H = 0.2
LAMBDA = 0.05
WEIGHTS = [1.25, 1]
NUM_SIMULATIONS = 10

setup_model(NUM_AGENTS, INITIAL_VARIANT_OCCURENCE, H, LAMBDA, WEIGHTS, NUM_SIMULATIONS)