from model import *

NUM_AGENTS = 5
INITIAL_VARIANT_OCCURENCE = 0.34
H = 0.1
LAMBDA = 0.02
WEIGHTS = [1.0008, 1]
NUM_SIMULATIONS = 1
NUM_CHILD_PER_ADULT = 3

setup_model(NUM_AGENTS, INITIAL_VARIANT_OCCURENCE, H, LAMBDA, WEIGHTS, NUM_SIMULATIONS, NUM_CHILD_PER_ADULT)